name: habit-tracker-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
     - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}