name: todo-list-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
     - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}